// Captures Backchannel app screenshots for the product showcase and docs.
//
// Usage:  node showcase/capture.mjs            (app running at localhost:3000)
//         node showcase/capture.mjs --out DIR  (default: showcase/screenshots)
//
// Requires the fictional demo workspace: python showcase/seed_demo.py
// Playwright is reused from the product-showcase skill install.
//
// Every surface is captured in BOTH themes and each shot waits on real rendered
// content, then logs what it actually observed -- a blank panel or a wrong tab
// must not pass silently. Briefing and Chat need a configured LLM key; when none
// is present they are skipped with a notice rather than failing the run.
import { createRequire } from "module";
import { homedir } from "os";
import { mkdirSync } from "fs";
import { join } from "path";

const require = createRequire(join(homedir(), ".claude/skills/product-showcase/bin/package.json"));
const { chromium } = require("playwright");

const outArg = process.argv.indexOf("--out");
const OUT = outArg > -1 ? process.argv[outArg + 1] : "showcase/screenshots";
mkdirSync(OUT, { recursive: true });

const SESSION = "Northwind Logistics - segm";
const log = [];

// Briefing and Chat both call an LLM. Skip them when no provider is configured.
const creds = await fetch("http://localhost:3000/api/credentials").then((r) => r.json()).catch(() => []);
const hasKey = Array.isArray(creds) && creds.some((c) => c.key_available);
if (!hasKey) log.push("NOTE: no LLM key configured -- skipping briefing and chat shots");

const browser = await chromium.launch();

async function run(colorScheme, suffix) {
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, colorScheme });
  const shot = async (name, note) => {
    await page.screenshot({ path: `${OUT}/${name}${suffix}.png` });
    log.push(`  ${name}${suffix} -- ${note}`);
  };
  const tab = async (re) => {
    await page.getByRole("button", { name: re }).first().click();
    await page.waitForTimeout(700);
  };

  await page.goto("http://localhost:3000", { waitUntil: "networkidle" });
  const expand = page.locator('[aria-label="Expand sidebar"]');
  if (await expand.isVisible().catch(() => false)) await expand.click();

  await page.getByText(SESSION).first().click();
  await page.waitForTimeout(900);

  if (hasKey) {
    // The control is "Generate Briefing" when none exists yet and "Refresh
    // Briefing" once one does; the empty state reads "No briefing was generated".
    const empty = page.getByText(/No briefing was generated/i);
    if (await empty.isVisible().catch(() => false)) {
      await page.getByRole("button", { name: /(Generate|Refresh) Briefing/ }).first().click();
      await empty.waitFor({ state: "hidden", timeout: 240000 });
    }
    await page.getByText(/TOP \d+ OUTCOMES|OBJECTIVES/i).first().waitFor({ timeout: 240000 });
    await page.waitForTimeout(900);
    const panels = await page.evaluate(() =>
      (document.body.innerText.match(/TOP \d+ OUTCOMES|OBJECTIVES|RISKS?|NEXT STEPS/gi) || []).join(", "));
    await shot("postcall-briefing", `briefing rendered: ${panels || "panels not detected"}`);
  }

  // Anchor on structure, not on insight copy: the insight set is regenerated by
  // the analysis agents and its wording changes every run.
  await tab(/^Insights/);
  await page.getByText(/^ACTION ITEMS$/i).first().waitFor({ timeout: 20000 });
  const shown = await page.evaluate(() =>
    document.body.innerText.match(/TOTAL\s+(\d+)/)?.[1] ?? "?");
  await shot("postcall-insights", `insight cards rendered, TOTAL ${shown}`);

  await tab(/^Transcript/);
  await page.getByText("cyber insurance renews").first().waitFor({ timeout: 20000 });
  await shot("postcall-transcript", "transcript rendered");

  // "Dana" also matches hidden <option> elements in the merge selects, so anchor
  // on the panel heading rather than a speaker name.
  await tab(/^Speakers/);
  await page.getByText(/Speaker Name Mapping/i).first().waitFor({ timeout: 20000 });
  await page.waitForTimeout(400);
  await shot("postcall-speakers", "speaker mapping rendered");

  await page.getByText("Administration").first().click();
  await page.getByText("consolidated_analyst").first().waitFor({ timeout: 20000 }).catch(() => {});
  await page.waitForTimeout(700);
  const badge = await page.evaluate(() => {
    const b = [...document.querySelectorAll("button")].find((x) => /^Agents/.test(x.textContent.trim()));
    return b ? b.textContent.trim() : "NOT FOUND";
  });
  await shot("admin-agents", `tab badge: ${badge}`);

  for (const [re, name] of [
    [/Transcription & Audio/, "admin-transcription"],
    [/API Keys/, "admin-api-keys"],
    [/About/, "admin-about"],
  ]) {
    await page.getByRole("button", { name: re }).first().click();
    await page.waitForTimeout(800);
    await shot(name, "admin tab");
  }

  for (const [label, name] of [
    ["Offerings Catalog", "offerings-catalog"],
    ["Knowledge Sources", "knowledge-sources"],
  ]) {
    await page.getByText(label).first().click();
    await page.waitForTimeout(900);
    await shot(name, "tool panel");
  }

  await page.close();
}

log.push("light:");
await run("light", "");
log.push("dark:");
await run("dark", "-dark");
await browser.close();

console.log(log.join("\n"));
console.log(`\ndone -> ${OUT}`);
